version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3002:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - SESSION_SECRET=${SESSION_SECRET:-your-session-secret-here}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:3000}
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
